version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
       POSTGRES_PASSWORD: 'docker'
       POSTGRES_USER: 'docker'
    ports:
      - "5432:5432"